services:
  - type: web
    name: tr-web
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    domains:
      - app.taskratchet.com
    routes:
      - type: rewrite
        source: /login
        destination: /login/index.html
      - type: rewrite
        source: /register
        destination: /register/index.html
      - type: rewrite
        source: /*
        destination: /
